# End-to-End Optimization Suite

This notebook launches the broader Stage 3 end-to-end optimization batch.

It will:

- mine hard training samples using the current strongest staged-training checkpoint
- run multiple continuation presets automatically
- export a markdown summary and leaderboard

In [1]:
# Uncomment this once in a fresh online environment if needed.
# %pip install -q transformers datasets peft accelerate trl bitsandbytes pyyaml jsonschema

In [2]:
from pathlib import Path
import runpy
import sys


def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / 'configs').exists() and (candidate / 'src').exists():
            return candidate
    raise RuntimeError('Could not find project root')


PROJECT_ROOT = find_project_root(Path.cwd())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print('project_root =', PROJECT_ROOT)
script_path = PROJECT_ROOT / 'scripts' / 'run_end_to_end_optimization_suite.py'
print('script_path =', script_path)
runpy.run_path(str(script_path), run_name='__main__')

project_root = /home/lyan11/small-llm-structured-posttraining
script_path = /home/lyan11/small-llm-structured-posttraining/scripts/run_end_to_end_optimization_suite.py
project_root = /home/lyan11/small-llm-structured-posttraining
python = 3.13.11 | packaged by conda-forge | (main, Dec  6 2025, 11:24:03) [GCC 14.3.0]
cuda_available = True
device = NVIDIA H200 NVL
bf16_supported = True
miner_checkpoint_dir = /home/lyan11/small-llm-structured-posttraining/results/checkpoints/qwen25_3b_stage2_structure_then_semantics_v1
scheduled_presets = ['sts_v2_hard_only_x4_epoch1_lr5e5', 'sts_v2_full_plus_hard_x2_epoch2_lr1e4', 'sts_v2_full_plus_hard_x3_epoch2_lr1e4', 'sts_v2_full_plus_hard_x2_epoch2_lr5e5']
skip_completed = True
skip_existing_mining = True
train = 1993
val = 247
test = 254

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

The following generation flags are not valid and may be ignored: ['top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

mined 100 / 1993 train records
mined 200 / 1993 train records
mined 300 / 1993 train records
mined 400 / 1993 train records
mined 500 / 1993 train records
mined 600 / 1993 train records
mined 700 / 1993 train records
mined 800 / 1993 train records
mined 900 / 1993 train records
mined 1000 / 1993 train records
mined 1100 / 1993 train records
mined 1200 / 1993 train records
mined 1300 / 1993 train records
mined 1400 / 1993 train records
mined 1500 / 1993 train records
mined 1600 / 1993 train records
mined 1700 / 1993 train records
mined 1800 / 1993 train records
mined 1900 / 1993 train records
mining_summary =
{
  "num_train_records": 1993,
  "num_hard_records": 561,
  "hard_fraction": 0.2814851981936779,
  "hard_bucket_counts": {
    "complex": 43,
    "medium": 294,
    "simple": 224
  }
}

================================================================================
running preset = sts_v2_hard_only_x4_epoch1_lr5e5
================================================================================
train_subset_size = 2244
train_subset_bucket_counts = {'complex': 172, 'medium': 1176, 'simple': 896}

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/2244 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/2244 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/2244 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

train_loss = 0.3032814260099975
generated 25 / 254
generated 50 / 254
generated 75 / 254
generated 100 / 254
generated 125 / 254
generated 150 / 254
generated 175 / 254
generated 200 / 254
generated 225 / 254
generated 250 / 254
{
  "num_samples": 254,
  "valid_json_rate": 1.0,
  "schema_compliance_rate": 1.0,
  "field_exact_match": 0.8725841088045813,
  "end_to_end_exact_match": 0.33070866141732286,
  "error_counts": {
    "invalid_json": 0,
    "schema_violation": 0,
    "missing_required_field": 0,
    "enum_error": 0,
    "type_error": 0,
    "value_hallucination": 170,
    "extraction_omission": 0,
    "cross_field_inconsistency": 0
  }
}

================================================================================
running preset = sts_v2_full_plus_hard_x2_epoch2_lr1e4
================================================================================
train_subset_size = 3115
train_subset_bucket_counts = {'complex': 218, 'medium': 1980, 'simple': 917}

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/3115 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/3115 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/3115 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

train_loss = 0.22995761766725656
generated 25 / 254
generated 50 / 254
generated 75 / 254
generated 100 / 254
generated 125 / 254
generated 150 / 254
generated 175 / 254
generated 200 / 254
generated 225 / 254
generated 250 / 254
{
  "num_samples": 254,
  "valid_json_rate": 1.0,
  "schema_compliance_rate": 1.0,
  "field_exact_match": 0.9155332856120257,
  "end_to_end_exact_match": 0.5433070866141733,
  "error_counts": {
    "invalid_json": 0,
    "schema_violation": 0,
    "missing_required_field": 0,
    "enum_error": 0,
    "type_error": 0,
    "value_hallucination": 116,
    "extraction_omission": 0,
    "cross_field_inconsistency": 0
  }
}

================================================================================
running preset = sts_v2_full_plus_hard_x3_epoch2_lr1e4
================================================================================
train_subset_size = 3676
train_subset_bucket_counts = {'complex': 261, 'medium': 2274, 'simple': 1141}

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/3676 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/3676 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/3676 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

train_loss = 0.21361316649810128
generated 25 / 254
generated 50 / 254
generated 75 / 254
generated 100 / 254
generated 125 / 254
generated 150 / 254
generated 175 / 254
generated 200 / 254
generated 225 / 254
generated 250 / 254
{
  "num_samples": 254,
  "valid_json_rate": 1.0,
  "schema_compliance_rate": 1.0,
  "field_exact_match": 0.9022906227630637,
  "end_to_end_exact_match": 0.5039370078740157,
  "error_counts": {
    "invalid_json": 0,
    "schema_violation": 0,
    "missing_required_field": 0,
    "enum_error": 0,
    "type_error": 0,
    "value_hallucination": 126,
    "extraction_omission": 0,
    "cross_field_inconsistency": 0
  }
}

================================================================================
running preset = sts_v2_full_plus_hard_x2_epoch2_lr5e5
================================================================================
train_subset_size = 3115
train_subset_bucket_counts = {'complex': 218, 'medium': 1980, 'simple': 917}

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/3115 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/3115 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/3115 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

train_loss = 0.24651218068842984
generated 25 / 254
generated 50 / 254
generated 75 / 254
generated 100 / 254
generated 125 / 254
generated 150 / 254
generated 175 / 254
generated 200 / 254
generated 225 / 254
generated 250 / 254
{
  "num_samples": 254,
  "valid_json_rate": 1.0,
  "schema_compliance_rate": 1.0,
  "field_exact_match": 0.9108804581245526,
  "end_to_end_exact_match": 0.5354330708661418,
  "error_counts": {
    "invalid_json": 0,
    "schema_violation": 0,
    "missing_required_field": 0,
    "enum_error": 0,
    "type_error": 0,
    "value_hallucination": 118,
    "extraction_omission": 0,
    "cross_field_inconsistency": 0
  }
}
summary_path = /home/lyan11/small-llm-structured-posttraining/docs/results/end_to_end_optimization_batch_summary.md
leaderboard =
{'preset_name': 'sts_v2_full_plus_hard_x2_epoch2_lr1e4', 'experiment_name': 'qwen25_3b_stage3_sts_v2_full_plus_hard_x2_epoch2_lr1e4', 'status': 'completed', 'field_exact_match': 0.9155332856120257, 'end_to_end_exact_match': 0.5433070866141733}
{'preset_name': 'sts_v2_full_plus_hard_x2_epoch2_lr5e5', 'experiment_name': 'qwen25_3b_stage3_sts_v2_full_plus_hard_x2_epoch2_lr5e5', 'status': 'completed', 'field_exact_match': 0.9108804581245526, 'end_to_end_exact_match': 0.5354330708661418}
{'preset_name': 'sts_v2_full_plus_hard_x3_epoch2_lr1e4', 'experiment_name': 'qwen25_3b_stage3_sts_v2_full_plus_hard_x3_epoch2_lr1e4', 'status': 'completed', 'field_exact_match': 0.9022906227630637, 'end_to_end_exact_match': 0.5039370078740157}
{'preset_name': 'sts_v2_hard_only_x4_epoch1_lr5e5', 'experiment_name': 'qwen25_3b_stage3_sts_v2_hard_only_x4_epoch1_lr5e5', 'status': 'completed', 'field_exact_match': 0.8725841088045813, 'end_to_end_exact_match': 0.33070866141732286}

{'__name__': '__main__',
 '__doc__': None,
 '__package__': '',
 '__loader__': None,
 '__spec__': None,
 '__file__': '/home/lyan11/small-llm-structured-posttraining/scripts/run_end_to_end_optimization_suite.py',
 '__cached__': None,
 '__builtins__': {'__name__': 'builtins',
  '__doc__': "Built-in functions, types, exceptions, and other objects.\n\nThis module provides direct access to all 'built-in'\nidentifiers of Python; for example, builtins.len is\nthe full name for the built-in function len().\n\nThis module is not normally accessed explicitly by most\napplications, but can be useful in modules that provide\nobjects with the same name as a built-in value, but in\nwhich the built-in of that name is also needed.",
  '__package__': '',
  '__loader__': _frozen_importlib.BuiltinImporter,
  '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'),
  '__build_class__': <function __build_class__>,
  '__import__': <function __import__(name, globals=None, locals=None, fromlist=(), level=0)>,
  'abs': <function abs(x, /)>,
  'all': <function all(iterable, /)>,
  'any': <function any(iterable, /)>,
  'ascii': <function ascii(obj, /)>,
  'bin': <function bin(number, /)>,
  'breakpoint': <function breakpoint(*args, **kws)>,
  'callable': <function callable(obj, /)>,
  'chr': <function chr(i, /)>,
  'compile': <function compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1, *, _feature_version=-1)>,
  'delattr': <function delattr(obj, name, /)>,
  'dir': <function dir>,
  'divmod': <function divmod(x, y, /)>,
  'eval': <function eval(source, /, globals=None, locals=None)>,
  'exec': <function exec(source, /, globals=None, locals=None, *, closure=None)>,
  'format': <function format(value, format_spec='', /)>,
  'getattr': <function getattr>,
  'globals': <function globals()>,
  'hasattr': <function hasattr(obj, name, /)>,
  'hash': <function hash(obj, /)>,
  'hex': <function hex(number, /)>,
  'id': <function id(obj, /)>,
  'input': <bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x7eb29004b380>>,
  'isinstance': <function isinstance(obj, class_or_tuple, /)>,
  'issubclass': <function issubclass(cls, class_or_tuple, /)>,
  'iter': <function iter>,
  'aiter': <function aiter(async_iterable, /)>,
  'len': <function len(obj, /)>,
  'locals': <function locals()>,
  'max': <function max>,
  'min': <function min>,
  'next': <function next>,
  'anext': <function anext>,
  'oct': <function oct(number, /)>,
  'ord': <function ord(character, /)>,
  'pow': <function pow(base, exp, mod=None)>,
  'print': <function print(*args, sep=' ', end='\n', file=None, flush=False)>,
  'repr': <function repr(obj, /)>,
  'round': <function round(number, ndigits=None)>,
  'setattr': <function setattr(obj, name, value, /)>,
  'sorted': <function sorted(iterable, /, *, key=None, reverse=False)>,
  'sum': <function sum(iterable, /, start=0)>,
  'vars': <function vars>,
  'None': None,
  'Ellipsis': Ellipsis,
  'NotImplemented': NotImplemented,
  'False': False,
  'True': True,
  'bool': bool,
  'memoryview': memoryview,
  'bytearray': bytearray,
  'bytes': bytes,
  'classmethod': classmethod,
  'complex': complex,
  'dict': dict,
  'enumerate': enumerate,
  'filter': filter,
  'float': float,
  'frozenset': frozenset,
  'property': property,
  'int': int,
  'list': list,
  'map': map,
  'object': object,
  'range': range,
  'reversed': reversed,
  'set': set,
  'slice': slice,
  'staticmethod': staticmethod,
  'str': str,
  'super': super,
  'tuple': tuple,
  'type': type,
  'zip': zip,
  '__debug__': True,
  'BaseException': BaseException,
  'BaseExceptionGroup': BaseExceptionGroup,
  'Exception': Exception,
  'GeneratorExit': GeneratorExit,
  'KeyboardInterrupt': KeyboardInterrupt,
  'SystemExit': SystemExit,
  'ArithmeticError': ArithmeticError,
  'AssertionError': AssertionError,
  'AttributeError': AttributeError,
  'BufferError': BufferError,
  'EOFError': EOFError,
  'ImportError': ImportError,
  'LookupError': LookupError,
  'MemoryError': MemoryError,
  'NameError': NameError,
  'OSError': OSError,
  'ReferenceError': ReferenceError,
  'RuntimeError': RuntimeError,
  'StopAsyncIteration': StopAsyncIteration,
  'StopIteration': StopIteration,
  'SyntaxError': SyntaxError,
  'SystemError': SystemError,
  'TypeError': TypeError,
  'ValueError': ValueError,
  'Warning': Warning,
  'FloatingPointError': FloatingPointError,
  'OverflowError': OverflowError,
  'ZeroDivisionError': ZeroDivisionError,
  'BytesWarning': BytesWarning,
  'DeprecationWarning': DeprecationWarning,
  'EncodingWarning': EncodingWarning,
  'FutureWarning': FutureWarning,
  'ImportWarning': ImportWarning,
  'PendingDeprecationWarning': PendingDeprecationWarning,
  'ResourceWarning': ResourceWarning,
  'RuntimeWarning': RuntimeWarning,
  'SyntaxWarning': SyntaxWarning,
  'UnicodeWarning': UnicodeWarning,
  'UserWarning': UserWarning,
  'BlockingIOError': BlockingIOError,
  'ChildProcessError': ChildProcessError,
  'ConnectionError': ConnectionError,
  'FileExistsError': FileExistsError,
  'FileNotFoundError': FileNotFoundError,
  'InterruptedError': InterruptedError,
  'IsADirectoryError': IsADirectoryError,
  'NotADirectoryError': NotADirectoryError,
  'PermissionError': PermissionError,
  'ProcessLookupError': ProcessLookupError,
  'TimeoutError': TimeoutError,
  'IndentationError': IndentationError,
  '_IncompleteInputError': _IncompleteInputError,
  'IndexError': IndexError,
  'KeyError': KeyError,
  'ModuleNotFoundError': ModuleNotFoundError,
  'NotImplementedError': NotImplementedError,
  'PythonFinalizationError': PythonFinalizationError,
  'RecursionError': RecursionError,
  'UnboundLocalError': UnboundLocalError,
  'UnicodeError': UnicodeError,
  'BrokenPipeError': BrokenPipeError,
  'ConnectionAbortedError': ConnectionAbortedError,
  'ConnectionRefusedError': ConnectionRefusedError,
  'ConnectionResetError': ConnectionResetError,
  'TabError': TabError,
  'UnicodeDecodeError': UnicodeDecodeError,
  'UnicodeEncodeError': UnicodeEncodeError,
  'UnicodeTranslateError': UnicodeTranslateError,
  'ExceptionGroup': ExceptionGroup,
  'EnvironmentError': OSError,
  'IOError': OSError,
  'open': <function _io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
  'copyright': Copyright (c) 2001-2024 Python Software Foundation.
  All Rights Reserved.

  Copyright (c) 2000 BeOpen.com.
  All Rights Reserved.

  Copyright (c) 1995-2001 Corporation for National Research Initiatives.
  All Rights Reserved.

  Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
  All Rights Reserved.,
  'credits': Thanks to CWI, CNRI, BeOpen, Zope Corporation, the Python Software
  Foundation, and a cast of thousands for supporting Python
  development.  See www.python.org for more information.,
  'license': Type license() to see the full license text,
  'help': Type help() for interactive help, or help(object) for help about object.,
  'execfile': <function _pydev_bundle._pydev_execfile.execfile(file, glob=None, loc=None)>,
  'runfile': <function _pydev_bundle.pydev_umd.runfile(filename, args=None, wdir=None, namespace=None)>,
  '__IPYTHON__': True,
  'display': <function IPython.core.display_functions.display(*objs, include=None, exclude=None, metadata=None, transient=None, display_id=None, raw=False, clear=False, **kwargs)>,
  'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x7eb276ce52b0>>},
 'annotations': _Feature((3, 7, 0, 'beta', 1), None, 16777216),
 'gc': <module 'gc' (built-in)>,
 'json': <module 'json' from '/opt/conda/lib/python3.13/json/__init__.py'>,
 'random': <module 'random' from '/opt/conda/lib/python3.13/random.py'>,
 'sys': <module 'sys' (built-in)>,
 'defaultdict': collections.defaultdict,
 'Path': pathlib._local.Path,
 'torch': <module 'torch' from '/opt/conda/lib/python3.13/site-packages/torch/__init__.py'>,
 'load_dataset': <function datasets.load.load_dataset(path: str, name: Optional[str] = None, data_dir: Optional[str] = None, data_files: Union[str, collections.abc.Sequence[str], collections.abc.Mapping[str, Union[str, collections.abc.Sequence[str]]], NoneType] = None, split: Union[str, datasets.splits.Split, list[str], list[datasets.splits.Split], NoneType] = None, cache_dir: Optional[str] = None, features: Optional[datasets.features.features.Features] = None, download_config: Optional[datasets.download.download_config.DownloadConfig] = None, download_mode: Union[datasets.download.download_manager.DownloadMode, str, NoneType] = None, verification_mode: Union[datasets.utils.info_utils.VerificationMode, str, NoneType] = None, keep_in_memory: Optional[bool] = None, save_infos: bool = False, revision: Union[datasets.utils.version.Version, str, NoneType] = None, token: Union[bool, str, NoneType] = None, streaming: bool = False, num_proc: Optional[int] = None, storage_options: Optional[dict] = None, **config_kwargs) -> Union[datasets.dataset_dict.DatasetDict, datasets.arrow_dataset.Dataset, datasets.dataset_dict.IterableDatasetDict, datasets.iterable_dataset.IterableDataset]>,
 'PeftModel': peft.peft_model.PeftModel,
 'AutoModelForCausalLM': transformers.models.auto.modeling_auto.AutoModelForCausalLM,
 'AutoTokenizer': transformers.models.auto.tokenization_auto.AutoTokenizer,
 'BitsAndBytesConfig': transformers.utils.quantization_config.BitsAndBytesConfig,
 'TrainingArguments': transformers.training_args.TrainingArguments,
 'SFTTrainer': trl.trainer.sft_trainer.SFTTrainer,
 'PROJECT_ROOT': PosixPath('/home/lyan11/small-llm-structured-posttraining'),
 'dump_jsonl': <function src.data.io.dump_jsonl(path: 'str | Path', records: 'list[dict[str, Any]]') -> 'None'>,
 'load_jsonl': <function src.data.io.load_jsonl(path: 'str | Path') -> 'list[dict[str, Any]]'>,
 'analyze_field_errors': <function src.evaluation.field_analysis.analyze_field_errors(gold_records: 'list[dict[str, Any]]', pred_records: 'list[dict[str, Any]]') -> 'dict[str, Any]'>,
 'evaluate_sample': <function src.evaluation.metrics.evaluate_sample(sample_id: 'str', prediction_text: 'str | None', prediction_json: 'dict[str, Any] | None', target_json: 'dict[str, Any]', schema: 'dict[str, Any]') -> 'SampleEvaluation'>,
 'summarize_results': <function src.evaluation.metrics.summarize_results(results: 'list[SampleEvaluation]') -> 'dict[str, Any]'>,
 'try_parse_prediction_text': <function src.evaluation.metrics.try_parse_prediction_text(prediction_text: 'str') -> 'tuple[bool, dict[str, Any] | None]'>,
 'group_sample_results': <function src.evaluation.reporting.group_sample_results(sample_results: 'list[dict[str, Any]]', group_field: 'str') -> 'dict[str, list[dict[str, Any]]]'>,
 'write_json_report': <function src.evaluation.reporting.write_json_report(path: 'str | Path', report: 'dict[str, Any]') -> 'None'>,
 'repair_prediction': <function src.inference.repair.repair_prediction(prediction: 'dict[str, Any] | None', schema: 'dict[str, Any]') -> 'tuple[dict[str, Any] | None, bool]'>,
 'get_schema': <function src.schemas.registry.get_schema(schema_name: 'str') -> 'dict'>,
 'DEFAULT_SYSTEM_PROMPT': 'You are an information extraction model. Return only JSON that matches the requested schema. Do not add explanations or markdown.',
 'build_user_prompt': <function src.training.formatters.build_user_prompt(input_text: 'str', task_name: 'str', schema_name: 'str', include_schema_definition: 'bool' = False) -> 'str'>,
 'convert_to_sft_records': <function src.training.formatters.convert_to_sft_records(samples: 'list[dict[str, Any]]', include_schema_definition: 'bool' = False) -> 'list[dict[str, Any]]'>,
 'BASE_MODEL_NAME': 'Qwen/Qwen2.5-3B-Instruct',
 'SCHEMA_NAME': 'ticket_schema_v1_reduced',
 'MINER_CHECKPOINT_DIR': PosixPath('/home/lyan11/small-llm-structured-posttraining/results/checkpoints/qwen25_3b_stage2_structure_then_semantics_v1'),
 'ARTIFACT_DIR': PosixPath('/home/lyan11/small-llm-structured-posttraining/data/stage3_end_to_end_optimization'),
 'SUMMARY_PATH': PosixPath('/home/lyan11/small-llm-structured-posttraining/docs/results/end_to_end_optimization_batch_summary.md'),
 'RUN_PRESETS': ['sts_v2_hard_only_x4_epoch1_lr5e5',
  'sts_v2_full_plus_hard_x2_epoch2_lr1e4',
  'sts_v2_full_plus_hard_x3_epoch2_lr1e4',
  'sts_v2_full_plus_hard_x2_epoch2_lr5e5'],
 'SKIP_COMPLETED': True,
 'SKIP_EXISTING_MINING': True,
 'PRESETS': {'sts_v2_hard_only_x4_epoch1_lr5e5': {'experiment_name': 'qwen25_3b_stage3_sts_v2_hard_only_x4_epoch1_lr5e5',
   'base_model': 'Qwen/Qwen2.5-3B-Instruct',
   'schema_name': 'ticket_schema_v1_reduced',
   'init_from_checkpoint': PosixPath('/home/lyan11/small-llm-structured-posttraining/results/checkpoints/qwen25_3b_stage2_structure_then_semantics_v1'),
   'learning_rate': 5e-05,
   'epochs': 1,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'data_mode': 'hard_only',
   'hard_repeat': 4},
  'sts_v2_full_plus_hard_x2_epoch2_lr1e4': {'experiment_name': 'qwen25_3b_stage3_sts_v2_full_plus_hard_x2_epoch2_lr1e4',
   'base_model': 'Qwen/Qwen2.5-3B-Instruct',
   'schema_name': 'ticket_schema_v1_reduced',
   'init_from_checkpoint': PosixPath('/home/lyan11/small-llm-structured-posttraining/results/checkpoints/qwen25_3b_stage2_structure_then_semantics_v1'),
   'learning_rate': 0.0001,
   'epochs': 2,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'data_mode': 'full_plus_hard',
   'hard_repeat': 2},
  'sts_v2_full_plus_hard_x3_epoch2_lr1e4': {'experiment_name': 'qwen25_3b_stage3_sts_v2_full_plus_hard_x3_epoch2_lr1e4',
   'base_model': 'Qwen/Qwen2.5-3B-Instruct',
   'schema_name': 'ticket_schema_v1_reduced',
   'init_from_checkpoint': PosixPath('/home/lyan11/small-llm-structured-posttraining/results/checkpoints/qwen25_3b_stage2_structure_then_semantics_v1'),
   'learning_rate': 0.0001,
   'epochs': 2,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'data_mode': 'full_plus_hard',
   'hard_repeat': 3},
  'sts_v2_full_plus_hard_x2_epoch2_lr5e5': {'experiment_name': 'qwen25_3b_stage3_sts_v2_full_plus_hard_x2_epoch2_lr5e5',
   'base_model': 'Qwen/Qwen2.5-3B-Instruct',
   'schema_name': 'ticket_schema_v1_reduced',
   'init_from_checkpoint': PosixPath('/home/lyan11/small-llm-structured-posttraining/results/checkpoints/qwen25_3b_stage2_structure_then_semantics_v1'),
   'learning_rate': 5e-05,
   'epochs': 2,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'data_mode': 'full_plus_hard',
   'hard_repeat': 2}},
 'IMPORTANT_FIELDS': ['actions_requested[0].action',
  'affected_systems[0].component',
  'category',
  'priority'],
 'GENERATION_KWARGS': {'max_new_tokens': 256,
  'do_sample': False,
  'temperature': 1.0,
  'top_p': 1.0},
 'USE_BF16': True,
 'BNB_CONFIG': BitsAndBytesConfig {
   "_load_in_4bit": true,
   "_load_in_8bit": false,
   "bnb_4bit_compute_dtype": "bfloat16",
   "bnb_4bit_quant_storage": "uint8",
   "bnb_4bit_quant_type": "nf4",
   "bnb_4bit_use_double_quant": true,
   "llm_int8_enable_fp32_cpu_offload": false,
   "llm_int8_has_fp16_weight": false,
   "llm_int8_skip_modules": null,
   "llm_int8_threshold": 6.0,
   "load_in_4bit": true,
   "load_in_8bit": false,
   "quant_method": "bitsandbytes"
 },
 'bucket_counts': <function __main__.bucket_counts(records: 'list[dict]') -> 'dict[str, int]'>,
 'build_output_paths': <function __main__.build_output_paths(experiment_name: 'str') -> 'dict[str, Path]'>,
 'load_tokenizer': <function __main__.load_tokenizer(base_model_name: 'str')>,
 'load_base_model': <function __main__.load_base_model(base_model_name: 'str')>,
 'load_trainable_adapter_model': <function __main__.load_trainable_adapter_model(base_model_name: 'str', checkpoint_dir: 'Path')>,
 'build_training_args': <function __main__.build_training_args(config: 'dict', output_dir: 'Path', num_epochs: 'int')>,
 'build_trainer': <function __main__.build_trainer(model, dataset, tokenizer, config: 'dict', output_dir: 'Path', num_epochs: 'int')>,
 'load_chat_dataset': <function __main__.load_chat_dataset(train_file: 'Path', validation_file: 'Path', tokenizer)>,
 'write_sft_split': <function __main__.write_sft_split(records: 'list[dict]', path: 'Path') -> 'Path'>,
 'build_inference_messages': <function __main__.build_inference_messages(record: 'dict') -> 'list[dict]'>,
 'generate_prediction_text': <function __main__.generate_prediction_text(model, tokenizer, record: 'dict') -> 'str'>,
 'extract_field': <function __main__.extract_field(obj: 'dict | None', field_name: 'str')>,
 'analyze_train_hardness': <function __main__.analyze_train_hardness(records: 'list[dict]', predictions: 'list[dict]')>,
 'sample_eval_dicts': <function __main__.sample_eval_dicts(gold_records: 'list[dict]', pred_records: 'list[dict]', schema: 'dict')>,
 'summarize_from_dicts': <function __main__.summarize_from_dicts(sample_results: 'list[dict]')>,
 'outputs_complete': <function __main__.outputs_complete(paths: 'dict[str, Path]') -> 'bool'>,
 'cleanup_model': <function __main__.cleanup_model(*objects)>,
 'run': <function __main__.run()>}