# Action Canonicalization Suite

This notebook launches a larger target-design overnight batch that canonicalizes the `actions_requested[0].action` field using a category-conditioned template.

It batch-runs:

- single-stage canonical-action runs at multiple epoch settings
- staged canonical-action runs at multiple learning-rate / stage-2-duration settings

In [1]:
# Uncomment this once in a fresh online environment if needed.
# %pip install -q transformers datasets peft accelerate trl bitsandbytes pyyaml jsonschema

In [2]:
from pathlib import Path
import runpy
import sys


def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / 'configs').exists() and (candidate / 'src').exists():
            return candidate
    raise RuntimeError('Could not find project root')


PROJECT_ROOT = find_project_root(Path.cwd())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print('project_root =', PROJECT_ROOT)
script_path = PROJECT_ROOT / 'scripts' / 'run_action_canonicalization_suite.py'
print('script_path =', script_path)
runpy.run_path(str(script_path), run_name='__main__')

project_root = /home/lyan11/small-llm-structured-posttraining
script_path = /home/lyan11/small-llm-structured-posttraining/scripts/run_action_canonicalization_suite.py
project_root = /home/lyan11/small-llm-structured-posttraining
python = 3.13.11 | packaged by conda-forge | (main, Dec  6 2025, 11:24:03) [GCC 14.3.0]
cuda_available = True
device = NVIDIA H200 NVL
bf16_supported = True
scheduled_presets = ['canonical_action_single_stage_epoch5_lr2e4', 'canonical_action_single_stage_epoch7_lr2e4', 'canonical_action_single_stage_epoch9_lr2e4', 'canonical_action_structure_then_semantics_v1', 'canonical_action_structure_then_semantics_v1_lr1e4', 'canonical_action_structure_then_semantics_stage2_epoch7', 'canonical_action_structure_then_semantics_stage2_epoch9', 'canonical_action_structure_then_semantics_stage2_epoch7_lr1e4']
skip_completed = True
train = 1993
val = 247
test = 254
train_bucket_counts = {'complex': 132, 'medium': 1392, 'simple': 469}

================================================================================
running preset = canonical_action_single_stage_epoch5_lr2e4
================================================================================

================================================================================
running preset = canonical_action_single_stage_epoch7_lr2e4
================================================================================

================================================================================
running preset = canonical_action_single_stage_epoch9_lr2e4
================================================================================

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1993 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

The following generation flags are not valid and may be ignored: ['top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

train_loss = 0.45015395360438704
generated 25 / 254
generated 50 / 254
generated 75 / 254
generated 100 / 254
generated 125 / 254
generated 150 / 254
generated 175 / 254
generated 200 / 254
generated 225 / 254
generated 250 / 254

================================================================================
running preset = canonical_action_structure_then_semantics_v1
================================================================================

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1861 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

stage1_train_loss = 0.9649408348536087

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1993 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

stage2_train_loss = 0.37733856534201
generated 25 / 254
generated 50 / 254
generated 75 / 254
generated 100 / 254
generated 125 / 254
generated 150 / 254
generated 175 / 254
generated 200 / 254
generated 225 / 254
generated 250 / 254

================================================================================
running preset = canonical_action_structure_then_semantics_v1_lr1e4
================================================================================

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1861 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

stage1_train_loss = 1.184489056215448

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1993 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

stage2_train_loss = 0.48254124020773265
generated 25 / 254
generated 50 / 254
generated 75 / 254
generated 100 / 254
generated 125 / 254
generated 150 / 254
generated 175 / 254
generated 200 / 254
generated 225 / 254
generated 250 / 254

================================================================================
running preset = canonical_action_structure_then_semantics_stage2_epoch7
================================================================================

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1861 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

stage1_train_loss = 0.9663867586750096

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1993 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

stage2_train_loss = 0.32076718183466635
generated 25 / 254
generated 50 / 254
generated 75 / 254
generated 100 / 254
generated 125 / 254
generated 150 / 254
generated 175 / 254
generated 200 / 254
generated 225 / 254
generated 250 / 254

================================================================================
running preset = canonical_action_structure_then_semantics_stage2_epoch9
================================================================================

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1861 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

stage1_train_loss = 0.9673365011053571

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1993 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

stage2_train_loss = 0.27246272521885195
generated 25 / 254
generated 50 / 254
generated 75 / 254
generated 100 / 254
generated 125 / 254
generated 150 / 254
generated 175 / 254
generated 200 / 254
generated 225 / 254
generated 250 / 254

================================================================================
running preset = canonical_action_structure_then_semantics_stage2_epoch7_lr1e4
================================================================================

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1861 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

stage1_train_loss = 1.1824642763299458

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1993 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

stage2_train_loss = 0.420663616689695
generated 25 / 254
generated 50 / 254
generated 75 / 254
generated 100 / 254
generated 125 / 254
generated 150 / 254
generated 175 / 254
generated 200 / 254
generated 225 / 254
generated 250 / 254
summary_path = /home/lyan11/small-llm-structured-posttraining/docs/results/action_canonicalization_batch_summary.md
leaderboard =
{'preset_name': 'canonical_action_single_stage_epoch7_lr2e4', 'experiment_name': 'qwen25_3b_stage6_canonical_action_single_stage_epoch7_lr2e4', 'status': 'skipped_existing', 'field_exact_match': 0.9341445955619184, 'end_to_end_exact_match': 0.6653543307086615}
{'preset_name': 'canonical_action_structure_then_semantics_stage2_epoch9', 'experiment_name': 'qwen25_3b_stage6_canonical_action_structure_then_semantics_stage2_epoch9', 'status': 'completed', 'field_exact_match': 0.9319971367215462, 'end_to_end_exact_match': 0.6653543307086615}
{'preset_name': 'canonical_action_structure_then_semantics_stage2_epoch7', 'experiment_name': 'qwen25_3b_stage6_canonical_action_structure_then_semantics_stage2_epoch7', 'status': 'completed', 'field_exact_match': 0.9312813171080887, 'end_to_end_exact_match': 0.65748031496063}
{'preset_name': 'canonical_action_single_stage_epoch5_lr2e4', 'experiment_name': 'qwen25_3b_stage6_canonical_action_single_stage_epoch5_lr2e4', 'status': 'skipped_existing', 'field_exact_match': 0.9201861130994989, 'end_to_end_exact_match': 0.6456692913385826}
{'preset_name': 'canonical_action_structure_then_semantics_stage2_epoch7_lr1e4', 'experiment_name': 'qwen25_3b_stage6_canonical_action_structure_then_semantics_stage2_epoch7_lr1e4', 'status': 'completed', 'field_exact_match': 0.9259126700071583, 'end_to_end_exact_match': 0.6456692913385826}
{'preset_name': 'canonical_action_structure_then_semantics_v1_lr1e4', 'experiment_name': 'qwen25_3b_stage6_canonical_action_structure_then_semantics_v1_lr1e4', 'status': 'completed', 'field_exact_match': 0.9244810307802434, 'end_to_end_exact_match': 0.6377952755905512}
{'preset_name': 'canonical_action_single_stage_epoch9_lr2e4', 'experiment_name': 'qwen25_3b_stage6_canonical_action_single_stage_epoch9_lr2e4', 'status': 'completed', 'field_exact_match': 0.9266284896206156, 'end_to_end_exact_match': 0.6338582677165354}
{'preset_name': 'canonical_action_structure_then_semantics_v1', 'experiment_name': 'qwen25_3b_stage6_canonical_action_structure_then_semantics_v1', 'status': 'completed', 'field_exact_match': 0.9294917680744452, 'end_to_end_exact_match': 0.6259842519685039}

{'__name__': '__main__',
 '__doc__': None,
 '__package__': '',
 '__loader__': None,
 '__spec__': None,
 '__file__': '/home/lyan11/small-llm-structured-posttraining/scripts/run_action_canonicalization_suite.py',
 '__cached__': None,
 '__builtins__': {'__name__': 'builtins',
  '__doc__': "Built-in functions, types, exceptions, and other objects.\n\nThis module provides direct access to all 'built-in'\nidentifiers of Python; for example, builtins.len is\nthe full name for the built-in function len().\n\nThis module is not normally accessed explicitly by most\napplications, but can be useful in modules that provide\nobjects with the same name as a built-in value, but in\nwhich the built-in of that name is also needed.",
  '__package__': '',
  '__loader__': _frozen_importlib.BuiltinImporter,
  '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'),
  '__build_class__': <function __build_class__>,
  '__import__': <function __import__(name, globals=None, locals=None, fromlist=(), level=0)>,
  'abs': <function abs(x, /)>,
  'all': <function all(iterable, /)>,
  'any': <function any(iterable, /)>,
  'ascii': <function ascii(obj, /)>,
  'bin': <function bin(number, /)>,
  'breakpoint': <function breakpoint(*args, **kws)>,
  'callable': <function callable(obj, /)>,
  'chr': <function chr(i, /)>,
  'compile': <function compile(source, filename, mode, flags=0, dont_inherit=False, optimize=-1, *, _feature_version=-1)>,
  'delattr': <function delattr(obj, name, /)>,
  'dir': <function dir>,
  'divmod': <function divmod(x, y, /)>,
  'eval': <function eval(source, /, globals=None, locals=None)>,
  'exec': <function exec(source, /, globals=None, locals=None, *, closure=None)>,
  'format': <function format(value, format_spec='', /)>,
  'getattr': <function getattr>,
  'globals': <function globals()>,
  'hasattr': <function hasattr(obj, name, /)>,
  'hash': <function hash(obj, /)>,
  'hex': <function hex(number, /)>,
  'id': <function id(obj, /)>,
  'input': <bound method Kernel.raw_input of <ipykernel.ipkernel.IPythonKernel object at 0x70c112297380>>,
  'isinstance': <function isinstance(obj, class_or_tuple, /)>,
  'issubclass': <function issubclass(cls, class_or_tuple, /)>,
  'iter': <function iter>,
  'aiter': <function aiter(async_iterable, /)>,
  'len': <function len(obj, /)>,
  'locals': <function locals()>,
  'max': <function max>,
  'min': <function min>,
  'next': <function next>,
  'anext': <function anext>,
  'oct': <function oct(number, /)>,
  'ord': <function ord(character, /)>,
  'pow': <function pow(base, exp, mod=None)>,
  'print': <function print(*args, sep=' ', end='\n', file=None, flush=False)>,
  'repr': <function repr(obj, /)>,
  'round': <function round(number, ndigits=None)>,
  'setattr': <function setattr(obj, name, value, /)>,
  'sorted': <function sorted(iterable, /, *, key=None, reverse=False)>,
  'sum': <function sum(iterable, /, start=0)>,
  'vars': <function vars>,
  'None': None,
  'Ellipsis': Ellipsis,
  'NotImplemented': NotImplemented,
  'False': False,
  'True': True,
  'bool': bool,
  'memoryview': memoryview,
  'bytearray': bytearray,
  'bytes': bytes,
  'classmethod': classmethod,
  'complex': complex,
  'dict': dict,
  'enumerate': enumerate,
  'filter': filter,
  'float': float,
  'frozenset': frozenset,
  'property': property,
  'int': int,
  'list': list,
  'map': map,
  'object': object,
  'range': range,
  'reversed': reversed,
  'set': set,
  'slice': slice,
  'staticmethod': staticmethod,
  'str': str,
  'super': super,
  'tuple': tuple,
  'type': type,
  'zip': zip,
  '__debug__': True,
  'BaseException': BaseException,
  'BaseExceptionGroup': BaseExceptionGroup,
  'Exception': Exception,
  'GeneratorExit': GeneratorExit,
  'KeyboardInterrupt': KeyboardInterrupt,
  'SystemExit': SystemExit,
  'ArithmeticError': ArithmeticError,
  'AssertionError': AssertionError,
  'AttributeError': AttributeError,
  'BufferError': BufferError,
  'EOFError': EOFError,
  'ImportError': ImportError,
  'LookupError': LookupError,
  'MemoryError': MemoryError,
  'NameError': NameError,
  'OSError': OSError,
  'ReferenceError': ReferenceError,
  'RuntimeError': RuntimeError,
  'StopAsyncIteration': StopAsyncIteration,
  'StopIteration': StopIteration,
  'SyntaxError': SyntaxError,
  'SystemError': SystemError,
  'TypeError': TypeError,
  'ValueError': ValueError,
  'Warning': Warning,
  'FloatingPointError': FloatingPointError,
  'OverflowError': OverflowError,
  'ZeroDivisionError': ZeroDivisionError,
  'BytesWarning': BytesWarning,
  'DeprecationWarning': DeprecationWarning,
  'EncodingWarning': EncodingWarning,
  'FutureWarning': FutureWarning,
  'ImportWarning': ImportWarning,
  'PendingDeprecationWarning': PendingDeprecationWarning,
  'ResourceWarning': ResourceWarning,
  'RuntimeWarning': RuntimeWarning,
  'SyntaxWarning': SyntaxWarning,
  'UnicodeWarning': UnicodeWarning,
  'UserWarning': UserWarning,
  'BlockingIOError': BlockingIOError,
  'ChildProcessError': ChildProcessError,
  'ConnectionError': ConnectionError,
  'FileExistsError': FileExistsError,
  'FileNotFoundError': FileNotFoundError,
  'InterruptedError': InterruptedError,
  'IsADirectoryError': IsADirectoryError,
  'NotADirectoryError': NotADirectoryError,
  'PermissionError': PermissionError,
  'ProcessLookupError': ProcessLookupError,
  'TimeoutError': TimeoutError,
  'IndentationError': IndentationError,
  '_IncompleteInputError': _IncompleteInputError,
  'IndexError': IndexError,
  'KeyError': KeyError,
  'ModuleNotFoundError': ModuleNotFoundError,
  'NotImplementedError': NotImplementedError,
  'PythonFinalizationError': PythonFinalizationError,
  'RecursionError': RecursionError,
  'UnboundLocalError': UnboundLocalError,
  'UnicodeError': UnicodeError,
  'BrokenPipeError': BrokenPipeError,
  'ConnectionAbortedError': ConnectionAbortedError,
  'ConnectionRefusedError': ConnectionRefusedError,
  'ConnectionResetError': ConnectionResetError,
  'TabError': TabError,
  'UnicodeDecodeError': UnicodeDecodeError,
  'UnicodeEncodeError': UnicodeEncodeError,
  'UnicodeTranslateError': UnicodeTranslateError,
  'ExceptionGroup': ExceptionGroup,
  'EnvironmentError': OSError,
  'IOError': OSError,
  'open': <function _io.open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)>,
  'copyright': Copyright (c) 2001-2024 Python Software Foundation.
  All Rights Reserved.

  Copyright (c) 2000 BeOpen.com.
  All Rights Reserved.

  Copyright (c) 1995-2001 Corporation for National Research Initiatives.
  All Rights Reserved.

  Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
  All Rights Reserved.,
  'credits': Thanks to CWI, CNRI, BeOpen, Zope Corporation, the Python Software
  Foundation, and a cast of thousands for supporting Python
  development.  See www.python.org for more information.,
  'license': Type license() to see the full license text,
  'help': Type help() for interactive help, or help(object) for help about object.,
  'execfile': <function _pydev_bundle._pydev_execfile.execfile(file, glob=None, loc=None)>,
  'runfile': <function _pydev_bundle.pydev_umd.runfile(filename, args=None, wdir=None, namespace=None)>,
  '__IPYTHON__': True,
  'display': <function IPython.core.display_functions.display(*objs, include=None, exclude=None, metadata=None, transient=None, display_id=None, raw=False, clear=False, **kwargs)>,
  'get_ipython': <bound method InteractiveShell.get_ipython of <ipykernel.zmqshell.ZMQInteractiveShell object at 0x70c100ee12b0>>},
 'annotations': _Feature((3, 7, 0, 'beta', 1), None, 16777216),
 'gc': <module 'gc' (built-in)>,
 'json': <module 'json' from '/opt/conda/lib/python3.13/json/__init__.py'>,
 'sys': <module 'sys' (built-in)>,
 'deepcopy': <function copy.deepcopy(x, memo=None, _nil=[])>,
 'Path': pathlib._local.Path,
 'torch': <module 'torch' from '/opt/conda/lib/python3.13/site-packages/torch/__init__.py'>,
 'load_dataset': <function datasets.load.load_dataset(path: str, name: Optional[str] = None, data_dir: Optional[str] = None, data_files: Union[str, collections.abc.Sequence[str], collections.abc.Mapping[str, Union[str, collections.abc.Sequence[str]]], NoneType] = None, split: Union[str, datasets.splits.Split, list[str], list[datasets.splits.Split], NoneType] = None, cache_dir: Optional[str] = None, features: Optional[datasets.features.features.Features] = None, download_config: Optional[datasets.download.download_config.DownloadConfig] = None, download_mode: Union[datasets.download.download_manager.DownloadMode, str, NoneType] = None, verification_mode: Union[datasets.utils.info_utils.VerificationMode, str, NoneType] = None, keep_in_memory: Optional[bool] = None, save_infos: bool = False, revision: Union[datasets.utils.version.Version, str, NoneType] = None, token: Union[bool, str, NoneType] = None, streaming: bool = False, num_proc: Optional[int] = None, storage_options: Optional[dict] = None, **config_kwargs) -> Union[datasets.dataset_dict.DatasetDict, datasets.arrow_dataset.Dataset, datasets.dataset_dict.IterableDatasetDict, datasets.iterable_dataset.IterableDataset]>,
 'LoraConfig': peft.tuners.lora.config.LoraConfig,
 'TaskType': <enum 'TaskType'>,
 'AutoModelForCausalLM': transformers.models.auto.modeling_auto.AutoModelForCausalLM,
 'AutoTokenizer': transformers.models.auto.tokenization_auto.AutoTokenizer,
 'BitsAndBytesConfig': transformers.utils.quantization_config.BitsAndBytesConfig,
 'TrainingArguments': transformers.training_args.TrainingArguments,
 'SFTTrainer': trl.trainer.sft_trainer.SFTTrainer,
 'PROJECT_ROOT': PosixPath('/home/lyan11/small-llm-structured-posttraining'),
 'dump_jsonl': <function src.data.io.dump_jsonl(path: 'str | Path', records: 'list[dict[str, Any]]') -> 'None'>,
 'load_jsonl': <function src.data.io.load_jsonl(path: 'str | Path') -> 'list[dict[str, Any]]'>,
 'analyze_field_errors': <function src.evaluation.field_analysis.analyze_field_errors(gold_records: 'list[dict[str, Any]]', pred_records: 'list[dict[str, Any]]') -> 'dict[str, Any]'>,
 'evaluate_sample': <function src.evaluation.metrics.evaluate_sample(sample_id: 'str', prediction_text: 'str | None', prediction_json: 'dict[str, Any] | None', target_json: 'dict[str, Any]', schema: 'dict[str, Any]') -> 'SampleEvaluation'>,
 'summarize_results': <function src.evaluation.metrics.summarize_results(results: 'list[SampleEvaluation]') -> 'dict[str, Any]'>,
 'try_parse_prediction_text': <function src.evaluation.metrics.try_parse_prediction_text(prediction_text: 'str') -> 'tuple[bool, dict[str, Any] | None]'>,
 'group_sample_results': <function src.evaluation.reporting.group_sample_results(sample_results: 'list[dict[str, Any]]', group_field: 'str') -> 'dict[str, list[dict[str, Any]]]'>,
 'write_json_report': <function src.evaluation.reporting.write_json_report(path: 'str | Path', report: 'dict[str, Any]') -> 'None'>,
 'repair_prediction': <function src.inference.repair.repair_prediction(prediction: 'dict[str, Any] | None', schema: 'dict[str, Any]') -> 'tuple[dict[str, Any] | None, bool]'>,
 'get_schema': <function src.schemas.registry.get_schema(schema_name: 'str') -> 'dict'>,
 'DEFAULT_SYSTEM_PROMPT': 'You are an information extraction model. Return only JSON that matches the requested schema. Do not add explanations or markdown.',
 'build_user_prompt': <function src.training.formatters.build_user_prompt(input_text: 'str', task_name: 'str', schema_name: 'str', include_schema_definition: 'bool' = False) -> 'str'>,
 'convert_to_sft_records': <function src.training.formatters.convert_to_sft_records(samples: 'list[dict[str, Any]]', include_schema_definition: 'bool' = False) -> 'list[dict[str, Any]]'>,
 'BASE_MODEL_NAME': 'Qwen/Qwen2.5-3B-Instruct',
 'SCHEMA_NAME': 'ticket_schema_v1_reduced',
 'ARTIFACT_DIR': PosixPath('/home/lyan11/small-llm-structured-posttraining/data/stage6_action_canonicalization'),
 'SUMMARY_PATH': PosixPath('/home/lyan11/small-llm-structured-posttraining/docs/results/action_canonicalization_batch_summary.md'),
 'RUN_PRESETS': ['canonical_action_single_stage_epoch5_lr2e4',
  'canonical_action_single_stage_epoch7_lr2e4',
  'canonical_action_single_stage_epoch9_lr2e4',
  'canonical_action_structure_then_semantics_v1',
  'canonical_action_structure_then_semantics_v1_lr1e4',
  'canonical_action_structure_then_semantics_stage2_epoch7',
  'canonical_action_structure_then_semantics_stage2_epoch9',
  'canonical_action_structure_then_semantics_stage2_epoch7_lr1e4'],
 'SKIP_COMPLETED': True,
 'PRESETS': {'canonical_action_single_stage_epoch5_lr2e4': {'experiment_name': 'qwen25_3b_stage6_canonical_action_single_stage_epoch5_lr2e4',
   'mode': 'full',
   'learning_rate': 0.0002,
   'epochs': 5,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'rank': 16,
   'alpha': 32,
   'dropout': 0.05},
  'canonical_action_single_stage_epoch7_lr2e4': {'experiment_name': 'qwen25_3b_stage6_canonical_action_single_stage_epoch7_lr2e4',
   'mode': 'full',
   'learning_rate': 0.0002,
   'epochs': 7,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'rank': 16,
   'alpha': 32,
   'dropout': 0.05},
  'canonical_action_single_stage_epoch9_lr2e4': {'experiment_name': 'qwen25_3b_stage6_canonical_action_single_stage_epoch9_lr2e4',
   'mode': 'full',
   'learning_rate': 0.0002,
   'epochs': 9,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'rank': 16,
   'alpha': 32,
   'dropout': 0.05},
  'canonical_action_structure_then_semantics_v1': {'experiment_name': 'qwen25_3b_stage6_canonical_action_structure_then_semantics_v1',
   'mode': 'two_stage_structure_semantics',
   'learning_rate': 0.0002,
   'stage1_epochs': 1,
   'stage2_epochs': 5,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'rank': 16,
   'alpha': 32,
   'dropout': 0.05,
   'structure_stage_buckets': ['simple', 'medium'],
   'structure_stage_include_schema_definition': True},
  'canonical_action_structure_then_semantics_v1_lr1e4': {'experiment_name': 'qwen25_3b_stage6_canonical_action_structure_then_semantics_v1_lr1e4',
   'mode': 'two_stage_structure_semantics',
   'learning_rate': 0.0001,
   'stage1_epochs': 1,
   'stage2_epochs': 5,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'rank': 16,
   'alpha': 32,
   'dropout': 0.05,
   'structure_stage_buckets': ['simple', 'medium'],
   'structure_stage_include_schema_definition': True},
  'canonical_action_structure_then_semantics_stage2_epoch7': {'experiment_name': 'qwen25_3b_stage6_canonical_action_structure_then_semantics_stage2_epoch7',
   'mode': 'two_stage_structure_semantics',
   'learning_rate': 0.0002,
   'stage1_epochs': 1,
   'stage2_epochs': 7,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'rank': 16,
   'alpha': 32,
   'dropout': 0.05,
   'structure_stage_buckets': ['simple', 'medium'],
   'structure_stage_include_schema_definition': True},
  'canonical_action_structure_then_semantics_stage2_epoch9': {'experiment_name': 'qwen25_3b_stage6_canonical_action_structure_then_semantics_stage2_epoch9',
   'mode': 'two_stage_structure_semantics',
   'learning_rate': 0.0002,
   'stage1_epochs': 1,
   'stage2_epochs': 9,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'rank': 16,
   'alpha': 32,
   'dropout': 0.05,
   'structure_stage_buckets': ['simple', 'medium'],
   'structure_stage_include_schema_definition': True},
  'canonical_action_structure_then_semantics_stage2_epoch7_lr1e4': {'experiment_name': 'qwen25_3b_stage6_canonical_action_structure_then_semantics_stage2_epoch7_lr1e4',
   'mode': 'two_stage_structure_semantics',
   'learning_rate': 0.0001,
   'stage1_epochs': 1,
   'stage2_epochs': 7,
   'batch_size': 8,
   'grad_accum': 4,
   'seed': 42,
   'rank': 16,
   'alpha': 32,
   'dropout': 0.05,
   'structure_stage_buckets': ['simple', 'medium'],
   'structure_stage_include_schema_definition': True}},
 'ACTION_PREFIX_BY_CATEGORY': {'task': 'Handle request',
  'bug': 'Investigate issue',
  'feature': 'Review and plan request',
  'incident': 'Investigate and mitigate incident',
  'question': 'Answer and clarify'},
 'GENERATION_KWARGS': {'max_new_tokens': 256,
  'do_sample': False,
  'temperature': 1.0,
  'top_p': 1.0},
 'USE_BF16': True,
 'BNB_CONFIG': BitsAndBytesConfig {
   "_load_in_4bit": true,
   "_load_in_8bit": false,
   "bnb_4bit_compute_dtype": "bfloat16",
   "bnb_4bit_quant_storage": "uint8",
   "bnb_4bit_quant_type": "nf4",
   "bnb_4bit_use_double_quant": true,
   "llm_int8_enable_fp32_cpu_offload": false,
   "llm_int8_has_fp16_weight": false,
   "llm_int8_skip_modules": null,
   "llm_int8_threshold": 6.0,
   "load_in_4bit": true,
   "load_in_8bit": false,
   "quant_method": "bitsandbytes"
 },
 'canonicalize_action': <function __main__.canonicalize_action(record: 'dict') -> 'dict'>,
 'bucket_counts': <function __main__.bucket_counts(records: 'list[dict]') -> 'dict[str, int]'>,
 'build_output_paths': <function __main__.build_output_paths(experiment_name: 'str') -> 'dict[str, Path]'>,
 'load_tokenizer': <function __main__.load_tokenizer()>,
 'load_base_model': <function __main__.load_base_model()>,
 'build_training_args': <function __main__.build_training_args(config: 'dict', output_dir: 'Path', num_epochs: 'float')>,
 'build_peft_config': <function __main__.build_peft_config(config: 'dict')>,
 'build_trainer': <function __main__.build_trainer(model, dataset, tokenizer, config: 'dict', output_dir: 'Path', num_epochs: 'float', peft_config=None)>,
 'load_chat_dataset': <function __main__.load_chat_dataset(train_file: 'Path', validation_file: 'Path', tokenizer)>,
 'write_sft_split': <function __main__.write_sft_split(records: 'list[dict]', path: 'Path', include_schema_definition: 'bool' = False) -> 'Path'>,
 'build_inference_messages': <function __main__.build_inference_messages(record: 'dict') -> 'list[dict]'>,
 'generate_prediction_text': <function __main__.generate_prediction_text(model, tokenizer, record: 'dict') -> 'str'>,
 'sample_eval_dicts': <function __main__.sample_eval_dicts(gold_records: 'list[dict]', pred_records: 'list[dict]', schema: 'dict')>,
 'summarize_from_dicts': <function __main__.summarize_from_dicts(sample_results: 'list[dict]')>,
 'outputs_complete': <function __main__.outputs_complete(paths: 'dict[str, Path]') -> 'bool'>,
 'cleanup_model': <function __main__.cleanup_model(*objects)>,
 'run': <function __main__.run()>}