# Component Canonicalization Suite

This notebook launches a smaller target-design batch focused on `affected_systems[0].component`.

It batch-runs:

- a `component-only` canonicalization control
- joint `action + component` canonicalization in single-stage training
- a joint staged variant using the strongest canonical-action recipe family

In [1]:
# Uncomment this once in a fresh online environment if needed.
# %pip install -q transformers datasets peft accelerate trl bitsandbytes pyyaml jsonschema

In [ ]:
from pathlib import Path
import runpy
import sys


def find_project_root(start: Path) -> Path:
    for candidate in [start, *start.parents]:
        if (candidate / 'configs').exists() and (candidate / 'src').exists():
            return candidate
    raise RuntimeError('Could not find project root')


PROJECT_ROOT = find_project_root(Path.cwd())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print('project_root =', PROJECT_ROOT)
script_path = PROJECT_ROOT / 'scripts' / 'run_component_canonicalization_suite.py'
print('script_path =', script_path)
runpy.run_path(str(script_path), run_name='__main__')

project_root = /home/lyan11/small-llm-structured-posttraining
script_path = /home/lyan11/small-llm-structured-posttraining/scripts/run_component_canonicalization_suite.py
project_root = /home/lyan11/small-llm-structured-posttraining
python = 3.13.11 | packaged by conda-forge | (main, Dec  6 2025, 11:24:03) [GCC 14.3.0]
cuda_available = True
device = NVIDIA H200 NVL
bf16_supported = True
scheduled_presets = ['canonical_component_only_single_stage_epoch7_lr2e4', 'canonical_action_component_single_stage_epoch5_lr2e4', 'canonical_action_component_single_stage_epoch7_lr2e4', 'canonical_action_component_structure_then_semantics_stage2_epoch9']
skip_completed = True
inference_batch_size = 16
train = 1993
val = 247
test = 254
component_mapping_stats = {'unique_names': 279, 'deterministic_name_fraction': 0.45161290322580644, 'weighted_majority_fraction': 0.6748620170597089}

================================================================================
running preset = canonical_component_only_single_stage_epoch7_lr2e4
================================================================================

================================================================================
running preset = canonical_action_component_single_stage_epoch5_lr2e4
================================================================================

================================================================================
running preset = canonical_action_component_single_stage_epoch7_lr2e4
================================================================================

================================================================================
running preset = canonical_action_component_structure_then_semantics_stage2_epoch9
================================================================================
train_bucket_counts = {'complex': 132, 'medium': 1392, 'simple': 469}

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1861 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1861 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None, 'pad_token_id': 151643}.

stage1_train_loss = 0.965333813327854

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Map:   0%|          | 0/1993 [00:00<?, ? examples/s]

Map:   0%|          | 0/247 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/1993 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/247 [00:00<?, ? examples/s]

The following generation flags are not valid and may be ignored: ['top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

stage2_train_loss = 0.27423738571281364